// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy5VVq8S_BCmok_-wxDYlXZ37bPpHpOZU',
    appId: '1:552321400892:web:f1c963696fcef166f7c339',
    messagingSenderId: '552321400892',
    projectId: 'chatapp-5df71',
    authDomain: 'chatapp-5df71.firebaseapp.com',
    storageBucket: 'chatapp-5df71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoD67jhKb37p-iaXq0RpQMxXD-cpC0c6A',
    appId: '1:552321400892:android:524dff929a047120f7c339',
    messagingSenderId: '552321400892',
    projectId: 'chatapp-5df71',
    storageBucket: 'chatapp-5df71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM5zF_mjWta6lsUAMhaQi-viWPH9BSc1U',
    appId: '1:552321400892:ios:83425f97c4838a7ef7c339',
    messagingSenderId: '552321400892',
    projectId: 'chatapp-5df71',
    storageBucket: 'chatapp-5df71.appspot.com',
    iosBundleId: 'com.example.chatAppWithBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM5zF_mjWta6lsUAMhaQi-viWPH9BSc1U',
    appId: '1:552321400892:ios:3b5902442d8ed177f7c339',
    messagingSenderId: '552321400892',
    projectId: 'chatapp-5df71',
    storageBucket: 'chatapp-5df71.appspot.com',
    iosBundleId: 'com.example.chatAppWithBloc.RunnerTests',
  );
}
